<a href="https://colab.research.google.com/github/siddharthanand25/siddharthanand25.github.io/blob/master/MLwithScikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random 
a= random.random()    # gives values in interval of (0 and 1)
a

0.8838988518294363

In [ ]:
a= random.randint(0,10)   #min value is zero and the maximum is 10
a

4

In [ ]:
import numpy as np, pandas as pd   #pandas is used for data cleansing and data analysisd= pd.da

In [ ]:
a= np.random.randn(2,3)
a

array([[-0.46241916, -1.54220202,  1.79188544],
       [-1.06267814, -0.23891476,  1.37687853]])

In [ ]:
d= pd.DataFrame(a)
d

0         1         2
0 -0.462419 -1.542202  1.791885
1 -1.062678 -0.238915  1.376879

In [ ]:
d.iloc[1]     # first index values


0   -1.062678
1   -0.238915
2    1.376879
Name: 1, dtype: float64

In [ ]:
d.iloc[1]  = np.nan
d                             #first index values

0         1         2
0 -0.462419 -1.542202  1.791885
1       NaN       NaN       NaN

In [ ]:
d.fillna(0)                  # does this temporary

0         1         2
0 -0.462419 -1.542202  1.791885
1  0.000000  0.000000  0.000000

In [ ]:
# how to we know which values are filled with what?   
d

0         1         2
0 -0.462419 -1.542202  1.791885
1       NaN       NaN       NaN

In [ ]:
d.fillna(d.mean(), inplace = True)       #inplace = True means you are filling data with the averages, we gereally fill values with mean data

In [ ]:
d        #-.04624 islye aaaya kyunki ek hee data tha      

0         1         2
0 -0.462419 -1.542202  1.791885
1 -0.462419 -1.542202  1.791885

In [ ]:
d                                         #inplace = True se tik ta hai data

0         1         2
0 -0.462419 -1.542202  1.791885
1 -0.462419 -1.542202  1.791885

In [ ]:
# normalizing the categorical features.
#now we are going for feature scaling : get all the values of same scale.(minmax scaling and standard scalar)          how we can work on text data, image data

#(minmax scaling and standard scalar): preprocessing techinques 
#Xnew = (X(i)- min(X)) /  (max(X)- min(X))    [normalisation]
from sklearn import preprocessing
data = { 'price': [492,286,452,482,325,754]}
s = pd.DataFrame(data)
s                                          #input dictionalry into a data frame

price
0    492
1    286
2    452
3    482
4    325
5    754

In [ ]:
min_max_normalizer = preprocessing.MinMaxScaler()
scaled_data =  min_max_normalizer.fit_transform(s)
scaled_data   # min value to 0 and maximum value to 1

array([[0.44017094],
       [0.        ],
       [0.35470085],
       [0.41880342],
       [0.08333333],
       [1.        ]])

In [ ]:
p = pd.DataFrame(scaled_data)
p

0
0  0.440171
1  0.000000
2  0.354701
3  0.418803
4  0.083333
5  1.000000

In [ ]:
#standard scalar: it standardise the feauture by removing the mean and scaling to unit variance    (mean and standar deviation use karta hai standard scalar)
from sklearn.preprocessing import  StandardScaler
data = np.array([[0,0], [0,0], [1,1], [1,1]])
scaler = StandardScaler()
scaler.fit(data)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [ ]:
#converting categorical data into numerical
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()           # you try to transform your text data into numericals
encoder.fit_transform(["Delhi","Pune","Mumbai","Agra", "Delhi"])     #transforming text into numericals


array([1, 3, 2, 0, 1])

In [ ]:
     encoder.classes_    #transformed into numerics

array(['Agra', 'Delhi', 'Mumbai', 'Pune'], dtype='<U6')

In [ ]:
sample = ["problem of evil","evil queen","horizon problem"]

# thats where we use count vectorizer for the above sample
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer() 

In [ ]:
X = vec.fit_transform(sample)
X

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [ ]:
pd.DataFrame(X.toarray(), columns=vec.get_feature_names())             #text analytics mein kaafi use hota hai ye sab


evil  horizon  of  problem  queen
0     1        0   1        1      0
1     1        0   0        0      1
2     0        1   0        1      0